// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEMJNuU63BMphdBZ4as01pnm1Q-pHIAYA',
    appId: '1:849278138709:web:033d6497f349f0ca3917dc',
    messagingSenderId: '849278138709',
    projectId: 'time-management-4120e',
    authDomain: 'time-management-4120e.firebaseapp.com',
    storageBucket: 'time-management-4120e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-t99rV5oDhLdL41MiZAVM5alQgYJ1Hy4',
    appId: '1:849278138709:android:fcb10d4c4ebfc9663917dc',
    messagingSenderId: '849278138709',
    projectId: 'time-management-4120e',
    storageBucket: 'time-management-4120e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCER8NTw3GSWuBDjAmk34PFmf-2rZ4XIhs',
    appId: '1:849278138709:ios:8485af0fe415bac13917dc',
    messagingSenderId: '849278138709',
    projectId: 'time-management-4120e',
    storageBucket: 'time-management-4120e.firebasestorage.app',
    iosBundleId: 'com.example.nhom10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCER8NTw3GSWuBDjAmk34PFmf-2rZ4XIhs',
    appId: '1:849278138709:ios:8485af0fe415bac13917dc',
    messagingSenderId: '849278138709',
    projectId: 'time-management-4120e',
    storageBucket: 'time-management-4120e.firebasestorage.app',
    iosBundleId: 'com.example.nhom10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEMJNuU63BMphdBZ4as01pnm1Q-pHIAYA',
    appId: '1:849278138709:web:7a73729d4dea992a3917dc',
    messagingSenderId: '849278138709',
    projectId: 'time-management-4120e',
    authDomain: 'time-management-4120e.firebaseapp.com',
    storageBucket: 'time-management-4120e.firebasestorage.app',
  );
}
